name: week 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        pip install flask
        pip install flask-sqlalchemy
        pip install pytest
    - name: Test
      run: 
        python -m pytest test.py -vv
