name: week 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        python -m pip install --upgrade pip
        pip freeze -r requirements.txt
    - name: Test
      run: python -m pytest test.py -vv
