name: week 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: 
        pip install -r requirements.txt
    - name: Test
      run: 
        python -m pytest test_api.py -vv
